#Location of query set
# For each query set we will run the experiments
#querySetLocation: '/home/eleicha/Documents/DFKI/Code/nebulastream/nes-benchmark/test/testData/'
querySetLocation: '/data-ssd/lmons-ldap/nes-remote/nes-benchmark/test/testData/'

# List of Query merging strategies in comma separated
#queryMergerRule: Z3SignatureBasedCompleteQueryMergerRule,SyntaxBasedCompleteQueryMergerRule,HybridCompleteQueryMergerRule,DefaultQueryMergerRule,HashSignatureBasedCompleteQueryMergerRule,ImprovedHashSignatureBasedCompleteQueryMergerRule,Z3SignatureBasedPartialQueryMergerBottomUpRule,Z3SignatureBasedBottomUpQueryContainmentRule
queryMergerRule: Z3SignatureBasedPartialQueryContainmentRule
#queryMergerRule: Z3SignatureBasedPartialQueryMergerRule,SyntaxBasedPartialQueryMergerRule,DefaultQueryMergerRule,HashSignatureBasedPartialQueryMergerRule,ImprovedHashSignatureBasedPartialQueryMergerRule,Z3SignatureBasedPartialQueryMergerBottomUpRule,Z3SignatureBasedPartialQueryContainmentRule,
# Number of Physical sources
noOfPhysicalSources: 1,1,1,1,1,1,1,1,1,1,1,1,1
# Batch size for processing number of queries together
batchSize: 1,1,1,1,1,1,1,1,1,1,1,1,1

#benchmark internal parameter
logLevel: LOG_ERROR
# Number of Distinct Logical sources
numberOfDistinctSources: 26
# Sleep interval between each run
startupSleepIntervalInSeconds: 3
# Number of times experiment is to be repeated
numberOfMeasurementsToCollect: 5
