---
# This Playbook runs monitoring tasks for a worker

- name: Get IP address from template
  set_fact:
    local_worker_ip: "{{ lookup('template', 'find-ip.j2') | trim }}"

- name: Remove older log
  file:
    path: "/home/ubuntu/dimitrios/worker_{{ local_worker_ip }}-sysStat.csv"
    state: absent

- name: Start dool monitoring
  shell: |
    nohup taskset -c 0 /home/ubuntu/git/{{ dool_name }}/{{ dool_name }} -tTcm -C 1,2,3 --output /home/ubuntu/dimitrios/worker_{{ local_worker_ip }}-sysStat.csv > /dev/null 2>&1 &

- name: Worker monitoring log is created
  wait_for:
    path: "/home/ubuntu/dimitrios/worker_{{ local_worker_ip }}-sysStat.csv"
