---
# This Playbook runs monitoring tasks for a worker

- name: Start dool monitoring
  shell: |
    nohup /home/ubuntu/git/{{ dool_name }}/{{ dool_name }} -tTcm -C {{ worker_cores }} --output /home/ubuntu/dimitrios/{{ ansible_hostname }}-sysStat.csv > /dev/null 2>&1 &
    echo $! > /home/ubuntu/dimitrios/{{ dool_name }}.pid

- name: Worker monitoring pid is created
  wait_for:
    path: "/home/ubuntu/dimitrios/{{ dool_name }}.pid"

- name: Worker monitoring log is created
  wait_for:
    path: "/home/ubuntu/dimitrios/{{ ansible_hostname }}-sysStat.csv"

- name: Read PID from file
  slurp:
    src: "/home/ubuntu/dimitrios/{{ dool_name }}.pid"
  register: pidfile_contents

- name: Convert PID file contents to string
  set_fact:
    worker_mon_pid: "{{ pidfile_contents['content'] | b64decode | trim }}"

- name: Check if process with PID is running
  shell: "ps -p {{ worker_mon_pid }} > /dev/null"
  register: ps_result
  ignore_errors: yes

- name: Set process running fact
  set_fact:
    process_running: "{{ ps_result.rc == 0 }}"

- name: Print message if PID is not running
  ansible.builtin.debug:
    msg: "Worker monitoring not running in {{ ansible_hostname }}."
  when: not process_running