---
# This Playbook starts a worker in the deployment

# TODO: install netstat
#- name: Gather occupied tcp v4 ports
#  shell: netstat -nlt4 | grep -oP '(?<=0.0.0.0:)(\d+)'
#  register: used_ports
#
#- name: Check if worker ports are free
#  set_fact:
#    bind_port: "{{ default_worker_ports | difference(used_ports.stdout_lines | map('int') | list) | first | default(0) }}"
#  failed_when: bind_port | int == 0

#- name: Start Worker (numa-controlled)
#  shell: |
#    sleep {{ last_octet }}
#    nohup numactl -N 0 -m 0 /home/{{ ansible_user_id | regex_replace(' ') }}/{{ cmake_build_dir }}/{{ worker_bin_name }} --configPath=/tmp/worker-conf.yaml > {{ worker_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ worker_bin_name }}.log 2>&1 &
#    echo $! > {{ worker_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ worker_bin_name }}.pid

- name: Start Worker
  shell: |
    nohup taskset -c 1-3 /home/ubuntu/git/nebulastream/build/nes-core/{{ worker_bin_name }} --configPath=/tmp/worker-conf-chameleon.yaml > /home/ubuntu/dimitrios/{{ worker_bin_name }}.log 2>&1 & 
    echo $! > /home/ubuntu/dimitrios/{{ worker_bin_name }}.pid

- name: Read PID from file
  slurp:
    src: "/home/ubuntu/dimitrios/{{ worker_bin_name }}.pid"
  register: pidfile_contents

- name: Convert PID file contents to string
  set_fact:
    worker_pid: "{{ pidfile_contents['content'] | b64decode | trim }}"

- name: Check if process with PID is running
  shell: "ps -p {{ worker_pid }} > /dev/null"
  register: ps_result
  ignore_errors: yes

- name: Set process running fact
  set_fact:
    process_running: "{{ ps_result.rc == 0 }}"

- name: Check that the log file exists
  stat:
    path: "/home/ubuntu/dimitrios/{{ worker_bin_name }}.log"
  register: stat_result

- name: Print message if PID is not running
  ansible.builtin.debug:
    msg: "Worker not not running."
  when: not process_running

- name: Print msg if file not found
  debug:
    msg: "Log file not found"
  when: stat_result.stat.exists == False