---
# This task kills the coordinator and its monitoring

- name: Find PIDs of dool
  shell: pgrep -f {{ dool_name }}
  register: dool_pids

- name: Kill PIDs
  shell: kill -9 {{ item }}
  loop: "{{ dool_pids.stdout_lines }}"
  when: dool_pids.stdout != ""

- name: Find PIDs of worker
  shell: pgrep -f {{ worker_bin_name }}
  register: worker_pids

- name: Kill PIDs
  shell: kill -9 {{ item }}
  loop: "{{ worker_pids.stdout_lines }}"
  when: worker_pids.stdout != ""
