apiVersion: apps/v1
kind: Deployment
metadata:
  name: nes-coordinator
  labels:
    app: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: Coordinator
  template:
    metadata:
      labels:
          app.kubernetes.io/name: Coordinator
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: coordinator-config
      containers:
        - name: coordinator
          image: nebulastream/nes-executable-image:latest
          volumeMounts:
            - mountPath: config-volume
              name: /config/coordinator.yaml
          ports:
            - containerPort: 8081
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator-service
spec:
  selector:
    app.kubernetes.io/name: Coordinator
  ports:
    - name: data-grpc
      protocol: TCP
      port: 4000
      targetPort: rpc-api
