# ~~~ Configurations for the NES E2E Selection Benchmark ~~~

#Location of query set
# For each query set we will run the experiments
querySetLocation: '/data-ssd/ankit/remote-dev/benchmark/src/Micro-Benchmarks/Query-Merger/QueryLoad'
#querySetLocation: '/home/ankit/dima/nes/benchmark/src/Micro-Benchmarks/Query-Merger/QueryLoad'

# Parameter that are changed per run with comma separated list
#queryMergerRule: Z3SignatureBasedCompleteQueryMergerRule
# Z3SignatureBasedPartialQueryMergerBottomUpRule,SyntaxBasedPartialQueryMergerRule,ImprovedStringSignatureBasedPartialQueryMergerRule,Z3SignatureBasedPartialQueryMergerRule
#,ImprovedStringSignatureBasedPartialQueryMergerRule,Z3SignatureBasedPartialQueryMergerRule
# Z3SignatureBasedCompleteQueryMergerRule,ImprovedStringSignatureBasedCompleteQueryMergerRule,SyntaxBasedCompleteQueryMergerRule
#,HybridCompleteQueryMergerRule,ImprovedStringSignatureBasedCompleteQueryMergerRule
queryMergerRule: DefaultQueryMergerRule,HashSignatureBasedCompleteQueryMergerRule,ImprovedStringSignatureBasedCompleteQueryMergerRule,Z3SignatureBasedCompleteQueryMergerRule,SyntaxBasedCompleteQueryMergerRule
#queryMergerRule: Z3SignatureBasedPartialQueryMergerRule,SyntaxBasedPartialQueryMergerRule,DefaultQueryMergerRule,StringSignatureBasedPartialQueryMergerRule,ImprovedStringSignatureBasedPartialQueryMergerRule,Z3SignatureBasedPartialQueryMergerBottomUpRule
noOfPhysicalSources: 1,1,1,1,1
batchSize: 1,1,1,1,1

#benchmark internal parameter
logLevel: LOG_ERROR
numberOfDistinctSources: 26
startupSleepIntervalInSeconds: 3
numberOfMeasurementsToCollect: 3
