query: SELECT * FROM tcp_source WHERE id > 123456789 INTO discard_sink
sink:
  name: discard_sink
  type: Discard
  config:
    filePath: "/tmp/discard_sink.csv"
logical:
  - name: tcp_source
    schema:
      - name: id
        type: UINT64
      - name: value
        type: UINT64
      - name: timestamp
        type: UINT64
physical:
  - logical: tcp_source
    parserConfig:
      type: CSV
    sourceConfig:
      type: TCP
      socketDomain: AF_INET
      socketType: SOCK_STREAM
      socketPort: 5010
      socketHost: localhost
      socketBufferSize: 2
      flushIntervalMS: 100