services:
  single-node:
    build:
      context: ${SINGLE_NODE_BUILD_DIR}
      dockerfile_inline: |
        FROM ubuntu:24.04 AS app
        ENV LLVM_TOOLCHAIN_VERSION=19
        RUN apt update -y && apt install curl gpg wget -y
        RUN curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor -o /etc/apt/keyrings/llvm-snapshot.gpg \
        && chmod a+r /etc/apt/keyrings/llvm-snapshot.gpg \
        && echo "deb [arch="$$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/"$$(. /etc/os-release && echo "$$VERSION_CODENAME")"/ llvm-toolchain-"$$(. /etc/os-release && echo "$$VERSION_CODENAME")"-$${LLVM_TOOLCHAIN_VERSION} main" > /etc/apt/sources.list.d/llvm-snapshot.list \
        && echo "deb-src [arch="$$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/"$$(. /etc/os-release && echo "$$VERSION_CODENAME")"/ llvm-toolchain-"$$(. /etc/os-release && echo "$$VERSION_CODENAME")"-$${LLVM_TOOLCHAIN_VERSION} main" >> /etc/apt/sources.list.d/llvm-snapshot.list \
        && apt update -y \
        && apt install -y libc++1-$${LLVM_TOOLCHAIN_VERSION} libc++abi1-$${LLVM_TOOLCHAIN_VERSION} libusb-1.0-0-dev
        
        RUN GRPC_HEALTH_PROBE_VERSION=v0.4.13 && \
          wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/$${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
          chmod +x /bin/grpc_health_probe
        
        COPY nes-single-node-worker /usr/bin
        ENTRYPOINT ["nes-single-node-worker"]
    volumes:
      - .:/tmp/nebulastream-public
      # - ${TEST_FILE_CACHE}:/test-file-cache
    working_dir: /tmp/nebulastream-public
    healthcheck:
      test: [ "CMD-SHELL", "/bin/grpc_health_probe", '-addr', 'localhost:8080']
    command: ['--worker.numberOfBuffersInGlobalBufferManager=20000']

  systest:
    build:
      context: ${SYSTEST_BUILD_DIR}
      dockerfile_inline: |
        FROM ubuntu:24.04 AS app
        ENV LLVM_TOOLCHAIN_VERSION=19
        RUN apt update -y && apt install curl gpg -y
        RUN curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor -o /etc/apt/keyrings/llvm-snapshot.gpg \
        && chmod a+r /etc/apt/keyrings/llvm-snapshot.gpg \
        && echo "deb [arch="$$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/"$$(. /etc/os-release && echo "$$VERSION_CODENAME")"/ llvm-toolchain-"$$(. /etc/os-release && echo "$$VERSION_CODENAME")"-$${LLVM_TOOLCHAIN_VERSION} main" > /etc/apt/sources.list.d/llvm-snapshot.list \
        && echo "deb-src [arch="$$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/"$$(. /etc/os-release && echo "$$VERSION_CODENAME")"/ llvm-toolchain-"$$(. /etc/os-release && echo "$$VERSION_CODENAME")"-$${LLVM_TOOLCHAIN_VERSION} main" >> /etc/apt/sources.list.d/llvm-snapshot.list \
        && apt update -y \
        && apt install -y libc++1-$${LLVM_TOOLCHAIN_VERSION} libc++abi1-$${LLVM_TOOLCHAIN_VERSION} libusb-1.0-0-dev
        
        COPY systest /usr/bin/
        ENTRYPOINT ["systest"]
    depends_on:
      - single-node
    volumes:
      - .:/tmp/nebulastream-public
    working_dir: /tmp/nebulastream-public
    command: ['-s', 'single-node:8080', '-e', 'large']
