---
# This Playbook collects and cleans all logs of all workers

- name: Transfer logs from worker to coordinator
  fetch:
    src: "{{ worker_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ ansible_hostname }}-sysStat.csv"
    dest: "/home/{{ ansible_user_id | regex_replace(' ') }}/worker-logs/"
    flat: true

