---
# This task kills the worker process

- name: Check if pid file exists
  stat:
    path: "{{ worker_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/worker.pid"
  register: stat_result

- name: Get process, if pid file exists
  when: stat_result.stat.exists
  shell: "cat {{ worker_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/worker.pid"
  register: cat_result

- name: Kill process
  shell: "kill -9 {{ item }}"
  with_items: cat_result.stdout_lines

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: cat_result.stdout_lines

- name: Remove pid file
  file:
    path: "{{ worker_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/worker.pid"
    state: absent