---
# This Playbook runs all the deployment tasks for a worker

- name: Determine Local Worker IP
  set_fact:
    local_worker_ip: "{{ lookup('template', 'find-ip.j2') | trim }}"

- name: Create the local-ssd log directory
  file:
    path: "{{ worker_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes"
    state: directory

- name: Clone dool repository
  git:
    repo: 'https://github.com/scottchiefbaker/dool.git'
    dest: "{{ worker_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ dool_name }}"
    update: no
    clone: yes

- name: Copy and populate configuration templates in tmp
  template:
    src: worker.yaml.j2
    dest: "/tmp/worker-conf.yaml"

- name: Copy and populate Chameleon template
  template:
    src: worker-chameleon.yaml.j2
    dest: "/tmp/worker-conf-chameleon.yaml"

- name: Copy and populate mosquitto template
  template:
    src: mosquitto.conf.j2
    dest: "/tmp/mosquitto.conf"

- name: Copy binaries directory to remote
  copy:
    src: ./binaries/
    dest: "{{ worker_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/"

- name: Install requirements
  pip:
    requirements: "{{ worker_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/requirements.txt"
