---
# This task kills the worker and its monitoring

- name: Find PIDs of dool
  shell: pgrep -f {{ dool_name }}
  register: dool_pids

- name: Kill PIDs
  shell: kill -9 {{ item }}
  loop: "{{ dool_pids.stdout_lines }}"
  when: dool_pids.stdout != ""
  ignore_errors: true

- name: Find PIDs of worker
  shell: pgrep -f {{ worker_bin_name }}
  register: worker_pids

- name: Kill PIDs
  shell: kill -9 {{ item }}
  loop: "{{ worker_pids.stdout_lines }}"
  when: worker_pids.stdout != ""
  ignore_errors: true

- name: Find PIDs of generator
  shell: pgrep -f e2e_latency
  register: generator_pids

- name: Kill PIDs
  shell: kill -9 {{ item }}
  loop: "{{ generator_pids.stdout_lines }}"
  when: generator_pids.stdout != ""
  ignore_errors: true

- name: Find PIDs of mosquitto
  shell: pgrep -f mosquitto
  register: mosquitto_pids

- name: Kill PIDs
  shell: kill -9 {{ item }}
  loop: "{{ mosquitto_pids.stdout_lines }}"
  when: mosquitto_pids.stdout != ""
  ignore_errors: true