apiVersion: v1
kind: Service
metadata:
  name: coordinator-service
spec:
  selector:
    app: coordinator
  ports:
    - protocol: TCP
      name: data
      port: {{ ports.data }}
    - protocol: TCP
      name: data-wl
      port: {{ ports.dataWL }}
    - protocol: TCP
      name: data-w
      port: {{ ports.dataW }}
    - protocol: TCP
      name: rest
      port: {{ ports.rest }}
    - protocol: TCP
      name: rpc
      port: {{ ports.rpc }}
    - protocol: TCP
      name: rpc-wl
      port: {{ ports.rpcWL }}
    - protocol: TCP
      name: rpc-w
      port: {{ ports.rpcW }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nes-coordinator
  labels:
    app: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: nes-ft
        image: {{ coordinator.image }}
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: {{ ports.rpc }}
        - containerPort: {{ ports.data }}
        - containerPort: {{ ports.rest }}
        - containerPort: {{ ports.dataWL }}
        - containerPort: {{ ports.rpcWL }}
        - containerPort: {{ ports.dataW }}
        - containerPort: {{ ports.rpcW }}
        command: ["nesCoordinator", "--coordinatorIp=$(MY_POD_IP)", "--restIp=0.0.0.0", "--rpcPort=10000", "--logLevel=LOG_DEBUG", "--worker.localWorkerIp=$(MY_POD_IP)", "--worker.coordinatorPort=10000", "--worker.dataPort=10001"]
        #command: ["nesCoordinator", "--coordinatorIp=$(MY_POD_IP)", "--restIp=0.0.0.0", "--rpcPort=10000", "--dataPort=10001", "--logLevel=LOG_WARNING", "--worker.localWorkerIp=$(MY_POD_IP)", "--worker.coordinatorPort=10000", "--worker.dataPort=10001", "--numberOfBuffersPerEpoch=900", "--numberOfBuffersInGlobalBufferManager=8192", "--numberOfBuffersInSourceLocalBufferPool=1024", "--bufferSizeInBytes=131072", "numWorkerThreads=4"]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nes-worker
  labels:
    app: worker
spec:
  replicas: {{worker.n_worker}}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: nes-ft
        image: {{worker.image}}
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: {{ ports.dataWL }}
        - containerPort: {{ ports.dataW }}
        - containerPort: {{ ports.rpcW }}
        - containerPort: {{ ports.rpc }}
        - containerPort: {{ ports.rpcWL }}
        - containerPort: {{ ports.data }}
        command: ["nesWorker", "--localWorkerIp=$(MY_POD_IP)", "--coordinatorIp=coordinator-service", "--coordinatorPort=10000", "--rpcPort=3000", "--dataPort=3001", "--logLevel=LOG_DEBUG", "--numberOfBuffersInGlobalBufferManager=8192", "--numberOfBuffersInSourceLocalBufferPool=1024", "--bufferSizeInBytes=131072", "--numWorkerThreads=4", "numberOfBuffersPerWorker=128"]


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nes-worker-source
  labels:
    app: worker
spec:
  replicas: {{worker.n_worker_sources}}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: nes-ft
        image: {{worker.image}}
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: {{ ports.dataWL }}
        - containerPort: {{ ports.dataW }}
        - containerPort: {{ ports.rpcW }}
        - containerPort: {{ ports.rpc }}
        - containerPort: {{ ports.rpcWL }}
        - containerPort: {{ ports.data }}
        command: ["nesWorker", "--physicalSources.type=DEFAULT_SOURCE", "--physicalSources.rowLayout=true", "--physicalSources.physicalSourceName=x", "--physicalSources.logicalSourceName=default_logical", "--physicalSources.numberOfBuffersToProduce=500","--localWorkerIp=$(MY_POD_IP)", "--coordinatorIp=coordinator-service", "--coordinatorPort=10000", "--rpcPort=3000", "--dataPort=3001", "--logLevel=LOG_DEBUG", "--numberOfBuffersInGlobalBufferManager=8192", "--numberOfBuffersInSourceLocalBufferPool=1024", "--bufferSizeInBytes=131072", "--numWorkerThreads=4", "numberOfBuffersPerWorker=128"]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
data:
  # property-like keys; each key maps to a simple value
  config_file_name: "worker.yaml"

