###
### Logical source configuration
###
logicalSources:
        # The name of the logical source.
        - logicalSourceName: "wind_turbines"
          # The description of the schema.
          fields:
                  - name: type
                    type: CHAR
                    length: 50
                  - name: metadata_generated
                    type: UINT64
                  - name: metadata_title
                    type: CHAR
                    length: 50
                  - name: metadata_id
                    type: CHAR
                    length: 50
                  - name: features_type
                    type: CHAR
                    length: 50
                  - name: features_properties_capacity
                    type: UINT64
                  - name: features_properties_efficiency
                    type: FLOAT32
                  - name: features_properties_mag
                    type: FLOAT32
                  - name: features_properties_time
                    type: UINT64
                  - name: features_properties_updated
                    type: UINT64
                  - name: features_properties_type
                    type: CHAR
                    length: 50
                  - name: features_geometry_type
                    type: CHAR
                    length: 50
                  - name: features_geometry_coordinates_longitude
                    type: FLOAT32
                  - name: features_geometry_coordinates_latitude
                    type: FLOAT32
                  - name: features_eventId
                    type: CHAR
                    length: 50