# ~~~ Configurations for the NES Worker ~~~

# ~~ IPs and Ports ~~
# Set IP address of NES Coordinator to which the NES Worker should connect
coordinatorIp: 127.0.0.1

# Set RPC Server port of NES Coordinator to which the NES Worker should connect
# Needs to be the same as rpcPort in Coordinator
coordinatorPort: 4000

# Set RPC server port of NES Worker
rpcPort: 3000

# Set the data port of the NES Worker
dataPort: 3001

# Set worker IP
localWorkerIp: 127.0.0.1

# Set parentId of NES Worker node
parentId: -1

# Set number of computing slots in NES Worker
# 0 is a place holder, default is number of processors installed in host machine
numberOfSlots: 0

# The log level (LOG_NONE, LOG_WARNING, LOG_DEBUG, LOG_INFO, LOG_TRACE)
logLevel: LOG_DEBUG

# Set the number of worker threads
numWorkerThreads: 1
