logLevel: LOG_INFO
localWorkerIp: 127.0.0.2
coordinatorIp: 127.0.0.1
numberOfSlots: 2147483647
numWorkerThreads: 8
bufferSizeInBytes: 8192
numberOfBuffersPerWorker: 128
numberOfBuffersInGlobalBufferManager: 4096
numberOfBuffersInSourceLocalBufferPool: 128
queryCompiler:
  queryCompilerNautilusBackendConfig: MLIR_COMPILER_BACKEND
workerId: 2
parentId: 0
dataPort: 9432
rpcPort: 9433
coordinatorPort: 8434
physicalSources:
 - type: TCP_SOURCE
   logicalSourceName: nexmark_bid
   physicalSourceName: nexmark_bid_1
   configuration:
     socketHost: 10.0.0.1
     socketPort: 8080
     socketDomain: AF_INET
     socketType: SOCK_STREAM
     flushIntervalMS: 100
     inputFormat: NES
     decideMessageSize: BUFFER_SIZE_FROM_SOCKET
     bytesUsedForSocketBufferSizeTransfer: 8
