# ~~~ Configurations for the NES Worker ~~~

# ~~ IPs and Ports ~~
# Set worker IP
localWorkerIp: 192.168.6.9

# Set IP address of NES Coordinator to which the NES Worker should connect
coordinatorIp: 192.168.6.181

# Set RPC Server port of NES Coordinator to which the NES Worker should connect
# Needs to be the same as rpcPort in Coordinator
coordinatorPort: 10000

# Set RPC server port of NES Worker
rpcPort: 3000

# Set the data port of the NES Worker
dataPort: 3001

# Set number of computing slots in NES Worker
numberOfSlots: 65535

# Set the number of worker threads
numWorkerThreads: 10

# Number buffers in global buffer pool
numberOfBuffersInGlobalBufferManager: 50000

# Number buffers in task local buffer pool
numberOfBuffersPerWorker: 1024

# Number buffers in source local buffer pool
numberOfBuffersInSourceLocalBufferPool: 1024

# Size of buffer to pass data through the system
bufferSizeInBytes: 4096

# Set parentId of NES Worker node
parentId: 0

# The log level (LOG_NONE, LOG_WARNING, LOG_DEBUG, LOG_INFO, LOG_TRACE)
logLevel: LOG_DEBUG

# Indicates the optimization strategy for the query compiler [FAST|DEBUG|OPTIMIZE]
queryCompilerCompilationStrategy: OPTIMIZE

# Indicates the pipelining strategy for the query compiler [OPERATOR_FUSION|OPERATOR_AT_A_TIME]
queryCompilerPipeliningStrategy: OPERATOR_FUSION

# Indicates the OutputBufferAllocationStrategy [ALL|NO|ONLY_INPLACE_OPERATIONS_NO_FALLBACK,
# |REUSE_INPUT_BUFFER_AND_OMIT_OVERFLOW_CHECK_NO_FALLBACK,|REUSE_INPUT_BUFFER_NO_FALLBACK|OMIT_OVERFLOW_CHECK_NO_FALLBACK]
queryCompilerOutputBufferOptimizationLevel: ALL

# Comma separated list of where to map the sources
sourcePinList:

# Comma separated list of where to map the worker
workerPinList:

# Enable Numa-Aware execution
numaAwareness: false

# Enable monitoring
enableMonitoring: false

# ~~~ Physical Stream Configurations ~~~

# A Physical Stream may be associated with multiple Instances of a logicalStreamName, a physicalStreamName and a SourceType
# If no Physical Stream Config is given, the worker will be created without a physical stream
# Available source Types: DefaultSource, CSVSource, MQTTSource, SenseSource, OPCSource (ToDo: Make source available),
#                         ZMQSource (ToDo: Make source available), KafkaSource (ToDo: Make source available),
#                         BinarySource (ToDo: Make source available))
physicalSources:
  # Set logical stream name where this stream is added to
  - logicalSourceName: A
    # Set physical stream name
    physicalSourceName: A1
    # Define source type, also need to specify source configurations for source type below
    type: MQTTSource
    # MQTTSource and its needed configuration params
    configuration:
      url: tcp://192.168.6.10:1883/
      clientId: 1
      userName: x
      topic: X
      qos: 1
      cleanSession: true
      flushIntervalMS: 10000
      inputFormat: JSON