---
# This task kills the coordinator

- name: Check if pid file exists
  stat:
    path: "{{ coord_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/cord.pid"
  register: stat_result

- name: Get process, if pid file exists
  when: stat_result.stat.exists
  shell: "cat {{ coord_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/cord.pid"
  register: cat_result

- name: Kill process
  shell: "kill -9 {{ item }}"
  with_items: cat_result.stdout_lines

- wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: cat_result.stdout_lines

- name: Remove pid file
  file:
    path: "{{ coord_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/cord.pid"
    state: absent