---
# This Playbook runs all the deployment tasks for a coordinator

- name: Create the log directory
  ignore_errors: true
  file:
    path: "/home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes"
    state: directory
