---
# This Playbook runs all the common plays in the deployment

- name: Create the log directory
  ignore_errors: true
  file:
    path: "{{ coord_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes"
    state: directory

- name: Start coordinator
  command: "numactl -N 0 -m 0 {{ coord_bin_name }} --configPath={{ coord_conf_file }} > {{ coord_bin_name }}.log"
  args:
    chdir: "{{ coord_root_dir }}/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes"
    creates: "{{ coord_bin_name }}.log"

  # TODO Log PID in file
