---
# This Playbook runs all the deployment tasks for a coordinator

- name: Create the log directory
  ignore_errors: true
  file:
    path: "/home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes"
    state: directory

- name: Copy and populate configuration template
  template:
    src: coordinator.yaml.j2
    dest: "/home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/coordinator.yaml"