---
# This Playbook runs a coordinator in the deployment

- name: Start coordinator
  shell: |
    nohup numactl -N 0 -m 0 /home/{{ ansible_user_id | regex_replace(' ') }}/{{ cmake_build_dir }}/{{ coord_bin_name }} > /home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ coord_bin_name }}.log 2>&1 & 
    echo $! > /home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ coord_bin_name }}.pid
