---
# This task kills the coordinator

- name: Check if pid file exists
  stat:
    path: "/home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ coord_bin_name }}.pid"
  register: stat_result

- name: Get process, if pid file exists
  when: stat_result.stat.exists
  shell: "cat /home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ coord_bin_name }}.pid"
  register: cat_result

- name: Kill process
  when: stat_result.stat.exists
  shell: "kill -9 {{ cat_result.stdout }}"
  ignore_errors: true

- name: Wait for process to completely die
  when: stat_result.stat.exists
  wait_for:
    path: "/proc/{{ cat_result.stdout }}/status"
    state: absent

- name: Remove pid file
  file:
    path: "/home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ coord_bin_name }}.pid"
    state: absent