---
# This task kills the coordinator and its monitoring

- name: Check if coordinator monitoring pid file exists
  stat:
    path: "/home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ dool_name }}.pid"
  register: mon_stat_result

- name: Get coordinator monitoring pid
  when: mon_stat_result.stat.exists
  shell: "cat /home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ dool_name }}.pid"
  register: mon_cat_result

- name: Kill coordinator monitoring
  when: mon_stat_result.stat.exists
  shell: "kill -9 {{ mon_cat_result.stdout }}"
  ignore_errors: true

- name: Wait for monitoring process to completely die
  when: mon_stat_result.stat.exists
  wait_for:
    path: "/proc/{{ mon_cat_result.stdout }}/status"
    state: absent

- name: Remove coordinator monitoring pid file
  file:
    path: "/home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ dool_name }}.pid"
    state: absent

- name: Check coordinator pid file exists
  stat:
    path: "/home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ coord_bin_name }}.pid"
  register: stat_result

- name: Get coordinator pid
  when: stat_result.stat.exists
  shell: "cat /home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ coord_bin_name }}.pid"
  register: cat_result

- name: Kill coordinator process
  when: stat_result.stat.exists
  shell: "kill -9 {{ cat_result.stdout }}"
  ignore_errors: true

- name: Wait for coordinator to completely die
  when: stat_result.stat.exists
  wait_for:
    path: "/proc/{{ cat_result.stdout }}/status"
    state: absent

- name: Remove coordinator pid file
  file:
    path: "/home/{{ ansible_user_id | regex_replace(' ') }}/{{ ansible_hostname }}-nes/{{ coord_bin_name }}.pid"
    state: absent