# ~~~ Configurations for the NES E2E Benchmark ~~~
numberOfWorkerThreads: 16, 8, 4, 1
bufferSizeInBytes: 10240
numberOfPreAllocatedBuffer: 10000
numberOfBuffersToProduce: 5000000

numberOfBuffersInGlobalBufferManager: 102400
numberOfBuffersPerPipeline: 10240
numberOfBuffersInSourceLocalBufferPool: 1024


# ~~~ Benchmark parameter for the entire run ~~~
logLevel: LOG_INFO
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 0
numberOfMeasurementsToCollect: 5

logicalSources:
  - name: input1
    type: Default
    minValue: 0
    maxValue: 10000
    numberOfPhysicalSources: 8

dataProvider: Internal
dataProviderMode: ZeroCopy
outputFile: FilterQuery.csv
benchmarkName: FilterQuery
query: 'Query::from("input1").filter(Attribute("value") < 2000).sink(NullOutputSinkDescriptor::create());'