query: |
  SELECT * FROM (SELECT * FROM tcp_source) INNER JOIN (SELECT * FROM tcp_source2)
  ON value = value2
  WINDOW SLIDING (timestamp, size 1 sec, advance by 250 ms)
  INTO csv_sink;
sink:
  name: csv_sink
  type: File
  config:
    inputFormat: CSV
    filePath: "GENERATE"
    append: false
logical:
  - name: tcp_source
    schema:
      - name: id
        type: UINT64
      - name: value
        type: UINT64
      - name: payload
        type: UINT64
      - name: timestamp
        type: UINT64
  - name: tcp_source2
    schema:
      - name: id2
        type: UINT64
      - name: value2
        type: UINT64
      - name: payload
        type: UINT64
      - name: timestamp
        type: UINT64
physical:
  - logical: tcp_source
    parserConfig:
      type: CSV
    sourceConfig:
      type: TCP
      socketDomain: AF_INET
      socketType: SOCK_STREAM
      socketPort: 5000
      socketHost: localhost
      socketBufferSize: 2
      flushIntervalMS: 100
  - logical: tcp_source2
    parserConfig:
      type: CSV
    sourceConfig:
      type: TCP
      socketDomain: AF_INET
      socketType: SOCK_STREAM
      socketPort: 5001
      socketHost: localhost
      socketBufferSize: 2
      flushIntervalMS: 100