# ~~~ Configurations for the NES E2E Benchmark ~~~

# Parameter that are changed per run with comma separated list
numberOfWorkerThreads: 8
numberOfCoordinatorThreads: 8
numberOfSources: 3

# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 100000,500000
numberOfBuffersPerPipeline: 1024,1024,1024
numberOfBuffersInSourceLocalBufferPool: 1024,1024,1024,1024,1024
bufferSizeInBytes: 4096,4096,4096,4096,4096

##benchmark parameter for the entire run
inputOutputMode: Auto
outputFile: out.csv
benchmarkName: testBench
query: 'Query::from("input").filter(Attribute("value") > 5).sink(NullOutputSinkDescriptor::create());'

#benchmark internal parameter
numberOfBuffersToProduce: 5000000
logLevel: LOG_WARNING
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 3
numberOfMeasurementsToCollect: 5

