# ~~~ Configurations for the NES E2E Benchmark ~~~
numberOfWorkerThreads: 1
numberOfBuffersInGlobalBufferManager: 1024
numberOfBuffersPerPipeline: 128
numberOfBuffersInSourceLocalBufferPool: 128
bufferSizeInBytes: 131072
numberOfPreAllocatedBuffer: 1000

# ~~~ Benchmark parameter for the entire run ~~~
numberOfBuffersToProduce: 500