# ~~~ Configurations for the NES E2E Benchmark ~~~
numberOfWorkerThreads: 1, 4, 8
bufferSizeInBytes: 4096
numberOfPreAllocatedBuffer: 10000
numberOfBuffersToProduce: 5000000

numberOfBuffersInGlobalBufferManager: 102400
numberOfBuffersPerPipeline: 1024
numberOfBuffersInSourceLocalBufferPool: 1024


# ~~~ Benchmark parameter for the entire run ~~~
logLevel: LOG_INFO
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 2
numberOfMeasurementsToCollect: 5

logicalSources:
  - name: input1
    type: Uniform
    minValue: 0
    maxValue: 10000
    numberOfPhysicalSources: 8

dataProvider: Internal
dataProviderMode: ZeroCopy
outputFile: DDSketch.csv
benchmarkName: DDSketch
query: 'Query::from("input1").buildStatistic(TumblingWindow::of(IngestionTime(), Milliseconds(1000)), Statistic::DDSketchDescriptor::create(Statistic::Over("value"), (double)error, (uint64_t)pre_allocated_buckets), 42, Statistic::SendingPolicyASAP::create(Statistic::StatisticDataCodec::DEFAULT), Statistic::NeverTrigger::create())
                               .sink(Statistic::StatisticSinkDescriptor::create(Statistic::StatisticSynopsisType::DD_SKETCH, Statistic::StatisticDataCodec::DEFAULT));'