---
# This Playbook runs all the deployment tasks for a coordinator

- name: Create the log directory
  ignore_errors: true
  file:
    path: "/home/ubuntu/dimitrios"
    state: directory

- name: Clone dool repository
  git:
    repo: 'https://github.com/scottchiefbaker/dool.git'
    dest: "/home/ubuntu/git/{{ dool_name }}"
    update: no
    clone: yes

- name: Copy and populate configuration template in tmp
  template:
    src: coordinator.yaml.j2
    dest: "/tmp/coordinator.yaml"

- name: Copy and populate mosquitto template
  template:
    src: mosquitto.conf.j2
    dest: "/tmp/mosquitto.conf"