---
# This Playbook runs a coordinator in the deployment

- name: Gather occupied tcp v4 ports
  shell: netstat -nlt4 | grep -oP '(?<=0.0.0.0:)(\d+)'
  register: used_ports

- name: Check if coordinator port is free
  set_fact:
    bind_port: "{{ default_coordinator_ports | difference(used_ports.stdout_lines | map('int') | list) | first | default(0) }}"
  failed_when: bind_port | int == 0

- name: Start mosquitto
  shell: |
    nohup mosquitto 2>&1 &
    echo $! > /home/ubuntu/dimitrios/mosquitto.pid

- name: Start Python data generator
  shell: |
    nohup python3 /home/ubuntu/dimitrios/e2e_latency.py > /home/ubuntu/dimitrios/generator.log &
    echo $! > /home/ubuntu/dimitrios/generator.pid

- name: Start coordinator
  shell: |
    nohup /home/ubuntu/git/nebulastream/build/nes-core/{{ coord_bin_name }} --configPath=/tmp/coordinator.yaml > /home/ubuntu/dimitrios/{{ coord_bin_name }}.log 2>&1 & 
    echo $! > /home/ubuntu/dimitrios/{{ coord_bin_name }}.pid

- name: Check that the log file exists
  stat:
    path: /home/ubuntu/dimitrios/{{ coord_bin_name }}.log
  register: stat_result

- debug:
    msg: "Log file not found"
  when: stat_result.stat.exists == False

- name: Deploy sensors schema
  uri:
    url: "http://{{ default_pi_master_ip}}:{{ default_coordinator_ports[0] }}/v1/nes/sourceCatalog/addLogicalSource"
    method: POST
    src: schemata/sensors.json
    headers:
      content-type: application/json
      cache-control: no-cache
