# This workflow builds and tests a ref, on a combination of different architectures and standard libraries.
name: Build and Test
on:
  workflow_call:
    inputs:
      dev_image_tag:
        required: true
        type: string
        description: "Docker image tag of the development image"
      ref:
        type: string
        required: true
        description: "ref of the branch"

jobs:
  build-and-test-arm:
    name: "Build and test arm64 with ${{matrix.stdlib}}"
    container:
      image: nebulastream/nes-development:${{ inputs.dev_image_tag }}-${{ matrix.stdlib }}
      volumes:
        - ccache:/ccache
      env:
        CCACHE_DIR: /ccache
        MOLD_JOBS: 1
      # TODO #401 Investigate rootless docker containers
      options: --user root
    timeout-minutes: 40
    runs-on: [ self-hosted, linux, Build, arm64 ]
    strategy:
      fail-fast: false
      matrix:
        stdlib: [ 'libstdcxx', 'libcxx' ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Configure NebulaStream
        run: cmake -GNinja -B build
      - name: Build NebulaStream
        run: cmake --build build -j -- -k 0
      - name: Run Tests
        # timeout of 600 seconds due to systest. Increase this number only if we encounter timeouts in our systests.
        run: ctest --test-dir build -j --output-on-failure --timeout 600

  build-and-test-x64:
    name: "Build and test x64 with ${{matrix.stdlib}}"
    container:
      image: nebulastream/nes-ci:${{ inputs.dev_image_tag }}-${{ matrix.stdlib }}
    timeout-minutes: 40
    runs-on: arc-large
    strategy:
      fail-fast: false
      matrix:
        stdlib: [ 'libstdcxx', 'libcxx' ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: show env
        run: printenv
      - name: Configure NebulaStream
        run: cmake -GNinja -B build
      - name: Build NebulaStream
        run: cmake --build build -j -- -k 0
      - name: Run Tests
        # timeout of 100 seconds due to systest. Increase this number only if we encounter timeouts in our systests.
        run: ctest --test-dir build -j --output-on-failure --timeout 100
