# This workflow calculates the development image tag of a ref. If the development image does not exist yet
# the workflow will build the new dependency image.
name: Dependency Image

on:
  workflow_call:
    inputs:
      branch-name:
        required: false
        type: string
        default: ${{ inputs.ref }}
        description: "Branch name to tag the docker image with"
      ref:
        required: true
        type: string
    outputs:
      image-tag:
        description: "Docker image tag for the current dependencies"
        value: ${{ jobs.detect-dependency-changes.outputs.tag }}

jobs:
  detect-dependency-changes:
    # This job detects changes to files relevant for our dependency management by calculating a hash value
    # and looking for existing development images with the same hash.
    # If we find a development image matching the hash we skip building new docker images.
    # This job also determines the development image tag used for building and testing
    name: Detect changes to dependencies
    outputs:
      build-dependency: ${{steps.hash-and-lookup.outputs.build-dependency}}
      tag: ${{ steps.hash-and-lookup.outputs.tag }}
      hash: ${{ steps.hash-and-lookup.outputs.hash }}
    runs-on: [ self-hosted, linux, Build ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Calculate and lookup hash
        id: hash-and-lookup
        run: |
          HASH=$(docker/dependency/hash_dependencies.sh)
          echo "Using Hash: $HASH"
          
          # Output the tag (hash) to GitHub Actions
          echo "tag=$HASH" >> "$GITHUB_OUTPUT"
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"
          
          if docker manifest inspect nebulastream/nes-ci:$HASH; then
            echo "build-dependency=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          
          # Check if jq is installed
          if ! command -v jq &> /dev/null; then
            echo "jq is not installed."
            exit 1
          fi
          
          # fetch all available tags for the nes-development image
          DOCKERHUB_RESPONSE=$(curl -s "https://hub.docker.com/v2/namespaces/nebulastream/repositories/nes-ci/tags?page_size=1000")
          if [ $? -ne 0 ]; then
            echo "could not fetch tags from the docker repository"
            exit 1
          fi
          
          TAGS=$(echo $DOCKERHUB_RESPONSE | jq ".results[].name")
          TAG_FOUND=$(echo $TAGS | jq -r "select (. == \"${HASH}\")")
          # Check if the Docker manifest exists for the computed hash
          if [[ "$TAG_FOUND" == "$HASH" ]]; then
            echo "build-dependency=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Development image with $HASH does not exist in the docker registry"
          echo "build-dependency=true" >> "$GITHUB_OUTPUT"
  build-dev-images:
    # We run the docker image build on separate machines and combine them into a single
    # multi-arch docker image in the docker-development-images job.
    # The Docker build uses a cache based on previous branch-specific images or the
    # main branch
    # This job builds a Base image which contains the llvm based toolchain and a recent
    # CMake version
    # The Dependency Image contains a pre-built sdk based on the vcpkg manifest
    # The Development Image contains the dependencies and additional tooling like clang-format.
    name: "Build Dev Images"
    needs: [ detect-dependency-changes ]
    if: needs.detect-dependency-changes.outputs.build-dependency == 'true'
    runs-on: [ self-hosted, linux, Build, "${{ matrix.arch }}", dep-builder ]
    strategy:
      fail-fast: false
      matrix:
        arch: [ x64, arm64 ]
        stdlib: [ 'libstdcxx', 'libcxx' ]
        sanitizer: [ 'Address', "Thread", "Undefined", null ]
        exclude:
          - arch: arm64
            stdlib: 'libstdcxx'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_SECRET }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.10.0
      - name: Build Base Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nebulastream/nes-development-base:${{ needs.detect-dependency-changes.outputs.tag }}-${{matrix.arch}}
          cache-to: type=registry,ref=nebulastream/nes-development-base-cache:${{inputs.branch-name}}-${{matrix.arch}},mode=max
          cache-from: |
            type=registry,ref=nebulastream/nes-development-base-cache:${{inputs.branch-name}}-${{matrix.arch}}
            type=registry,ref=nebulastream/nes-development-base-cache:latest-${{matrix.arch}}
          context: .
          file: docker/dependency/Base.dockerfile
      - name: Build Dependency Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nebulastream/nes-development-dependency:${{ needs.detect-dependency-changes.outputs.tag }}-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }}
          cache-to: type=registry,ref=nebulastream/nes-development-dependency-cache:${{inputs.branch-name}}-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }},mode=max
          cache-from: |
            type=registry,ref=nebulastream/nes-development-dependency-cache:${{inputs.branch-name}}-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }}
            type=registry,ref=nebulastream/nes-development-dependency-cache:latest-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }}
          build-args: |
            TAG=${{ needs.detect-dependency-changes.outputs.tag }}-${{matrix.arch}}
            ARCH=${{matrix.arch}}
            STDLIB=${{matrix.stdlib}}
            ENABLE_SANITIZER=${{matrix.sanitizer || 'None' }}
            VCPKG_DEPENDENCY_HASH=${{ needs.detect-dependency-changes.outputs.hash }}
          context: .
          file: docker/dependency/Dependency.dockerfile
      - name: Build Development Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nebulastream/nes-development:${{ needs.detect-dependency-changes.outputs.tag }}-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }}
          cache-to: type=registry,ref=nebulastream/nes-development-cache:${{inputs.branch-name}}-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }},mode=max
          cache-from: |
            type=registry,ref=nebulastream/nes-development-cache:${{inputs.branch-name}}-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }}
            type=registry,ref=nebulastream/nes-development-dependency-cache:latest-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }}
          build-args: TAG=${{ needs.detect-dependency-changes.outputs.tag }}-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }}
          context: .
          file: docker/dependency/Development.dockerfile
      - name: Build CI Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nebulastream/nes-ci:${{ needs.detect-dependency-changes.outputs.tag }}-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }}
          build-args: TAG=${{ needs.detect-dependency-changes.outputs.tag }}-${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.sanitizer || 'None' }}
          context: .
          file: docker/dependency/DevelopmentCI.dockerfile
      - name: Build benchmark image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nebulastream/nes-benchmark:${{ needs.detect-dependency-changes.outputs.tag }}-${{matrix.arch}}-${{matrix.stdlib}}
          build-args: TAG=${{ needs.detect-dependency-changes.outputs.tag }}-${{matrix.arch}}-${{matrix.stdlib}}
          context: .
          file: docker/dependency/Benchmark.dockerfile
  merge-dev-images:
    # This Job merges platform specific images into a single multi-platform image
    name: "Merge Dev Images"
    needs: [ build-dev-images, detect-dependency-changes ]
    if: needs.detect-dependency-changes.outputs.build-dependency == 'true'
    runs-on: [ self-hosted, linux, Build ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Login to Docker Hub
        if: ${{ !github.event.act }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_SECRET }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.10.0
      - name: Combine Manifests
        shell: bash
        # This script creates and tags Docker images for the NebulaStream development environment:
        # 1. Creates multi-arch (x64 + arm64) base development images
        # 2. For each standard library (libstdcxx, libcxx) and sanitizer (Address, Undefined, Thread, Node) combination:
        #    - Creates both development and development-dependency variants
        #    - Tags each image with both the dependency hash and branch name
        #   E.g., `nebulastream/nes-development:<branch-name>-libstdcxx-Address`
        # 3. Creates default development images using the libcxx-None configuration
        run: |
          docker buildx imagetools create -t nebulastream/nes-development-base:${{ needs.detect-dependency-changes.outputs.tag }} \
            nebulastream/nes-development-base:${{ needs.detect-dependency-changes.outputs.tag }}-x64 \
            nebulastream/nes-development-base:${{ needs.detect-dependency-changes.outputs.tag }}-arm64
          
          for image_tag in development-dependency development ci benchmark; do
            
            for sanitizer in None Address Thread Undefined; do
              docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-$sanitizer\
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-x64-libcxx-$sanitizer \
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-arm64-libcxx-$sanitizer
          
              docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-libcxx-$sanitizer \
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-x64-libcxx-$sanitizer \
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-arm64-libcxx-$sanitizer
          
              docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-libstdcxx-$sanitizer \
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-x64-libstdcxx-$sanitizer \
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-arm64-libstdcxx-$sanitizer 
            done
          
            # default image without sanitizer
            docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}\
              nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-None
          
            docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-libcxx-$sanitizer 
              nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-libcxx-None
          
            docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-libstdcxx-$sanitizer
              nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-libstdcxx-None
          
          
          done
      - name: Combine Manifests for branch specific docker image
        if: ${{ inputs.branch-name != '' }}
        run: |
          docker buildx imagetools create -t nebulastream/nes-development-base:${{ inputs.branch-name }} \
            nebulastream/nes-development-base:${{ needs.detect-dependency-changes.outputs.tag }}-x64 \
            nebulastream/nes-development-base:${{ needs.detect-dependency-changes.outputs.tag }}-arm64
          
          for image_tag in development-dependency development ci benchmark; do
          
            for sanitizer in None Address Thread Undefined; do
              docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ inputs.branch-name }}-$sanitizer \
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-x64-libcxx-$sanitizer \
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-arm64-libcxx-$sanitizer
          
              docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ inputs.branch-name }}-libcxx-$sanitizer \
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-x64-libcxx-$sanitizer \
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-arm64-libcxx-$sanitizer
          
              docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ inputs.branch-name }}-libstdcxx-$sanitizer \
                nebulastream/nes-$image_tag:${{ needs.detect-dependency-changes.outputs.tag }}-x64-libstdcxx-$sanitizer
            done
          
              docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ inputs.branch-name }} \
                  nebulastream/nes-$image_tag:${{ inputs.branch-name }}-None
          
              docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ inputs.branch-name }} \
                  nebulastream/nes-$image_tag:${{ inputs.branch-name }}-libcxx-None
          
              docker buildx imagetools create -t nebulastream/nes-$image_tag:${{ inputs.branch-name }} \
                  nebulastream/nes-$image_tag:${{ inputs.branch-name }}-libstdcxx-None
          done
