name: NES Benchmark

on:
  schedule:
    # executes every day at 1:15 am
    - cron: '15 1 * * *'
  workflow_dispatch:
    inputs:
      trigger-value:
        description: 'Trigger for performing benchmark on artifact release'
        required: false
        default: 'No_Value'

jobs:
  benchmark-scheduled-job:
    if: ${{ github.event.schedule }}
    runs-on: [self-hosted, linux, X64, Benchmark]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.CI_SECRET }}
          ssh-strict: 'false'
      - name: Fetch git history
        run: |
          git fetch --prune --unshallow --tags
      - name: Run benchmarks
        run: |
          docker run --name ${{ github.run_id }}_benchmark_scheduled -v $GITHUB_WORKSPACE:/nebulastream -v /etc/localtime:/etc/localtime:ro --entrypoint /nebulastream/docker/buildImage/entrypoint-nes-benchmark.sh nebulastream/nes-build-image:latest
      - name: Push Benchmarks to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CI_PERSONAL_TOKEN }}
          publish_dir: ./benchmark/scripts
          destination_dir: private/benchmark/
          exclude_assets: '*.py,*.so'
          keep_files: true
          external_repository: nebulastream/nes-server
          publish_branch: master
      - name: docker cleanup
        if: ${{ always() }}
        run: |
          docker rm -f ${{ github.run_id }}_benchmark_scheduled
  benchmark-triggered-job:
    if: "contains(github.event.inputs.trigger-value, 'trigger benchmark')"
    runs-on: [self-hosted, linux, X64, Benchmark]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.CI_SECRET }}
          ssh-strict: 'false'
      - name: Fetch git history
        run: |
          git fetch --prune --unshallow --tags
      - name: Run benchmarks
        run: |
          docker run --name ${{ github.run_id }}_benchmark_triggered -v $GITHUB_WORKSPACE:/nebulastream -v /etc/localtime:/etc/localtime:ro -e BENCHMARK_SCRIPT_ARGS='-f ../../build/benchmark/ -nc -m Run-with-docker -ba  e2e-benchmark-runner,--configPath=../../benchmark/src/E2EBenchmarks/CIRunningBenchmark/E2eMap.yaml           e2e-benchmark-runner,--configPath=../../benchmark/src/E2EBenchmarks/CIRunningBenchmark/E2eWindow.yaml          e2e-benchmark-runner,--configPath=../../benchmark/src/E2EBenchmarks/CIRunningBenchmark/E2eJoin.yaml  e2e-benchmark-runner,--configPath=../../benchmark/src/E2EBenchmarks/CIRunningBenchmark/E2eProjection.yaml e2e-benchmark-runner,--configPath=../../benchmark/src/E2EBenchmarks/CIRunningBenchmark/E2eSelection.yaml ' --entrypoint /nebulastream/docker/buildImage/entrypoint-nes-benchmark.sh nebulastream/nes-build-image:latest
          cp -R $GITHUB_WORKSPACE/benchmark/scripts/*.csv /tmp/benchmarks/.
      - name: docker cleanup
        if: ${{ always() }}
        run: |
          docker rm -f ${{ github.run_id }}_benchmark_triggered
