---
# This Playbook starts monitoring of a NES cluster

- hosts: pi_master
  tasks:
    - include_tasks: roles/pi-master/tasks/monitor.yml

- hosts: pi_worker
  gather_facts: yes
  tasks:
    - include_tasks: roles/pi-worker/tasks/monitor.yml