---
# This Playbook submits a query in a NES cluster

- hosts: pi_master
  tasks:
    - name: Submit avg query
      uri:
        url: "http://{{ default_pi_master_ip}}:{{ default_coordinator_ports[0] }}/v1/nes/query/execute-query"
        method: POST
        src: queries/sensor-avg.json
        status_code: 202
        headers:
          content-type: application/json
          cache-control: no-cache